services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ".env"
    environment:
      - DATABASE_PATH=/app/data
    volumes:
      - l_r_data:/app/data
    ports:
      - "7050:7050"

  database_init:
    build:
      context: database
      dockerfile: Dockerfile
    env_file:
      - ".env"
    environment:
      - DATABASE_PATH=/app/data
    volumes:
      - l_r_data:/app/data
  
  frontend:
    build:
      context: ..
      dockerfile: learning-resource-manager/frontend/Dockerfile
    volumes:
      - ./content:/content:ro
    ports:
      - "7051:80"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /usr/share/nginx/html
        - action: sync
          path: ../shared/assets
          target: /usr/share/nginx/html/assets
        - action: sync+restart
          path: ./frontend/nginx/default.conf
          target: /etc/nginx/conf.d/default.conf
        - action: rebuild
          path: ./frontend/Dockerfile

volumes:
  l_r_data:

